version: 0.1

phases:
  build:
    commands:
      - npm i
      - npm run webpack

artifacts:
  files:
    - index.html
    - favicon.ico
    - wesley.resume.pdf
    - styles/main.css
    - images/*
    - dist/bundle.js
