version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run webpack
      - npm run minify-css
artifacts:
  files:
    - index.html
    - favicon.ico
    - about.html
    - wesley.resume.no-contact-info.pdf
    - dist/*
